version: 2.1

orbs:
  node: circleci/node@0.0.9

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/install-package-manager:
          yarn: true
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn validate
